# Generated by Django 5.2.1 on 2025-07-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBodyBoards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('members', models.JSONField(default=list)),
            ],
        ),
        migrations.RenameField(
            model_name='boards',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
