# Generated by Django 5.2.1 on 2025-07-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_requestbodyboards_rename_owner_boards_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpret', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='boards',
            name='owner_id',
        ),
        migrations.DeleteModel(
            name='RequestBodyBoards',
        ),
        migrations.DeleteModel(
            name='Boards',
        ),
    ]
