# Generated by Django 5.2.1 on 2025-07-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_playlist_remove_boards_owner_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('member_count', models.PositiveSmallIntegerField(default=0)),
                ('ticket_count', models.PositiveSmallIntegerField(default=0)),
                ('tasks_to_do_count', models.PositiveSmallIntegerField(default=0)),
                ('tasks_high_prio_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
