# Generated by Django 5.2.1 on 2025-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0007_boards_members_alter_boards_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='to-do', max_length=10),
        ),
    ]
