# Generated by Django 5.2.1 on 2025-07-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0008_alter_tasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
